
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.example.analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MULTIPLICACION = 17;
  public static final int CADENA = 28;
  public static final int DECIMAL = 32;
  public static final int DIVISION = 18;
  public static final int SUMA = 15;
  public static final int ETIQUETAS = 8;
  public static final int EJECUTAR = 14;
  public static final int PORCENTAJE = 29;
  public static final int DOS_PUNTOS = 26;
  public static final int TIPO = 11;
  public static final int BARRAS = 3;
  public static final int VALORES = 9;
  public static final int COMA = 25;
  public static final int EOF = 0;
  public static final int TOTAL = 12;
  public static final int DEF = 2;
  public static final int PIE = 4;
  public static final int CANTIDAD = 30;
  public static final int EXTRA = 13;
  public static final int PARENTESIS_C = 20;
  public static final int error = 1;
  public static final int LLAVE_C = 22;
  public static final int PARENTESIS_A = 19;
  public static final int PUNTO_COMA = 27;
  public static final int LLAVE_A = 21;
  public static final int EJEY = 7;
  public static final int EJEX = 6;
  public static final int ENTERO = 31;
  public static final int COMENTARIO = 33;
  public static final int CORCHETE_C = 24;
  public static final int CORCHETE_A = 23;
  public static final int UNIR = 10;
  public static final int TITULO = 5;
  public static final int RESTA = 16;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DEF",
  "BARRAS",
  "PIE",
  "TITULO",
  "EJEX",
  "EJEY",
  "ETIQUETAS",
  "VALORES",
  "UNIR",
  "TIPO",
  "TOTAL",
  "EXTRA",
  "EJECUTAR",
  "SUMA",
  "RESTA",
  "MULTIPLICACION",
  "DIVISION",
  "PARENTESIS_A",
  "PARENTESIS_C",
  "LLAVE_A",
  "LLAVE_C",
  "CORCHETE_A",
  "CORCHETE_C",
  "COMA",
  "DOS_PUNTOS",
  "PUNTO_COMA",
  "CADENA",
  "PORCENTAJE",
  "CANTIDAD",
  "ENTERO",
  "DECIMAL",
  "COMENTARIO"
  };
}

